[profile.default]
solc = "0.8.30"
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
evm_version = "prague"

remappings = [
    "@gnosis.pm=node_modules/@gnosis.pm",
    "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@registries=lib/autonolas-registries",
]

[lint]
ignore = [
    "test/BridgeRelayer.sol",
]
exclude_lints = [
    "asm-keccak256",
    "erc20-unchecked-transfer",
    "mixed-case-function",
    "screaming-snake-case-immutable",
]