name: Workflow

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4

      # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
      
      # install poetry
      - name: poetry
        uses: python-poetry/poetry-action@v2.0.0
        with:
          poetry-version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Install modules
      - name: Install modules
        run: make install

      - name: Run formatting
        run: make fmt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint 'contracts/**/*.sol'

      # Compile the code and run tests
      - name: Compile the code
        run: forge build
      - name: Run tests
        run: forge test

      # Run hardhat coverage and upload codecov report
      #- name: Solidity coverage summary
      #  run: export NODE_OPTIONS="--max-old-space-size=8192" && forge coverage
