name: Workflow

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3

      # Install modules
      - name: Install modules
        run: make install

      - name: Run formatting
        run: make fmt

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint 'contracts/**/*.sol'

      # Compile the code and run tests and deploy script(s)
      - name: Compile the code
        run: ./node_modules/.bin/hardhat compile
      - name: Run Hardhat tests
        run: ./node_modules/.bin/hardhat test
      - name: Run Forge tests
        run: make tests
      

      # Run hardhat coverage and upload codecov report
      #- name: Solidity coverage summary
      #  run: export NODE_OPTIONS="--max-old-space-size=8192" && ./node_modules/.bin/hardhat coverage
